name: SCA

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false
  schedule:
    - cron: '16 2 * * 4'

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
                
      - name: Run SCA
        uses: tonycknight/pkgchk-action@v1.0.16
        with:
          deprecated: true
          vulnerable:  true
          transitives: true
          