name: SCA

permissions: 
  actions: read
  pull-requests: write
  security-events: write
  contents: write
  checks: write

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false
  schedule:
    - cron: '16 2 * * 4'

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
                
      - name: Run SCA
        uses: tonycknight/pkgchk-action@v1
        with:
          deprecated: true
          vulnerable:  true
          transitives: true
          